# Generated by Django 2.2.7 on 2019-11-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20191125_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='aapellidos',
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='titulo',
            field=models.TextField(help_text='Titulo'),
        ),
    ]
